quality_line = "ABBAAFFFFFFFGGGFGGGGGGHHHHHGHHHHHHHHHHFHHHHHHHGGGGGHFGGHHHHHHHHHHHHGHHGGHHHHHGHHFGGGGHHHHHHHHHHHHHHHHHHHGGGGGHHHHGGGFEEHHHHHHHHHGHHGGGHHHHHFGGFGHHHHFF"
print(len(quality_line))
quality_scores = [ord(char) - 33 for char in quality_line]

print(quality_scores)
