from Bio.Seq import Seq
my_seq = Seq("AGTACACTGTGT")
print(my_seq)
print(my_seq.find("ACT"))
print(my_seq.find("TAG"))
print(my_seq.count("A"))
print(my_seq.count('ACT'))
print(my_seq.count('TGT'))
print(my_seq.count_overlap('TGT'))
print(my_seq.complement())
print(my_seq.reverse_complement())
print(my_seq.transcribe())
my_rna = my_seq.transcribe()
print(my_rna)
print(my_rna.back_transcribe())
print(my_rna.back_transcribe().reverse_complement())
#Translation from RNA
messenger_rna = Seq("AUGGCCAUUGUAAUGGGCCGCUGAAAGGGUGCCCGAUAG")
print(messenger_rna.translate())
#Translation from DNA
coding_dna = Seq("AUGGCCAUUGUAAUGGGCCGCUGAAAGGGUGCCCGAUAG")
print(coding_dna.translate())
print(coding_dna.translate(to_stop=True))
print(coding_dna.translate(table=2))
