genes = ('a', 'e', 'i', 'o', 'i', 'u',"i","a")
count = genes.count('h')
print('h:', count)
count = genes.count('a')
print('a:', count)
count = genes.count('e')
print('e:', count)
count = genes.count('o')
print('o:', count)
count = genes.count('i')
print('i:', count)
count = genes.count('u')
print('u:', count)
